apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-rule
  namespace: monitoring
data:
  rules.yml: |
    groups:
      - name: rate-alerting
        rules:
          - alert: HighLogRate
            expr: |
              sum by (namespace)
                (rate({hostname=~"ck.+"}[1m]))
                > 60
            for: 1m
            labels:
                severity: warning
            annotations:
                title: "High LogRate Alert"
                description: "something is logging a lot"
                impact: "impact"
                action: "action"
                message: >-
                  {{ $labels.namespace }} namespace pods
                  are logging a lot.                                 
