apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-rule
  namespace: monitoring
data:
  rules.yml: |
    groups:
    - name: should_fire
      rules:
      - alert: HighPercentageError
        expr: |
          sum(rate({namespace="monitoring", pod_name="loki-0"} |= "error" [5m])) by (hostname)
            /
          sum(rate({namespace="monitoring", pod_name="loki-0"}[5m])) by (hostname)
            > 0.05
        for: 10m
        labels:
            severity: page
        annotations:
            summary: High request latency                  
